### PR TITLE
Update framework type information for SDK 10.0.18362.1

### PR DESCRIPTION
**Pull request by chausner**

### CODE REVIEW

**Comment by chausner** [comment]
I have published the code I used to extract this information here: https://github.com/chausner/XbfGenExtractor

**Comment by ge0rdi** [comment]
Hello @misenhower 
Will it be possible to merge this PR?
I'd like to contribute data from Win11 SDK as well as some changes regarding Win11 XBF decoding.

**Comment by chausner** [comment]
@ge0rdi I think unfortunately, this repo is no longer being maintained by @misenhower. If you want, feel free to contribute your changes to my fork where I have just merged these changes: https://github.com/chausner/XbfAnalyzer

**Comment by ge0rdi** [comment]
@chausner 
Cool, thank you.

I will have to put it together. As I was not working on this stuff for long time.
Though I'm definitely interested in contributing.

**Pull request closed without merging**
